version: '3.8'

services:
  boopato:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boopato
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DATABASE_PATH=/app/data/boopato.db
    volumes:
      - boopato-data:/app/data
    networks:
      - boopato-network

  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    container_name: boopato-watcher
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - boopato-repo:/app/boopato
      - boopato-logs:/var/log
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - boopato-network

volumes:
  boopato-data:
    name: boopato-data
  boopato-repo:
    name: boopato-repo
  boopato-logs:
    name: boopato-logs

networks:
  boopato-network:
    name: boopato-network