version: '3.8'

services:
  boopato:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boopato
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DATABASE_PATH=/app/data/boopato.db
    volumes:
      - boopato-data:/app/data
    networks:
      - boopato-network

  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    container_name: boopato-watcher
    restart: unless-stopped
    environment:
      - REPO_PATH=/app/boopato
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app/boopato
    networks:
      - boopato-network
    depends_on:
      - boopato

volumes:
  boopato-data:
    name: boopato-data

networks:
  boopato-network:
    name: boopato-network